package main

import "strings"

func init() {
	old := `<section id="platform" class="section"><div class="container"><div class="sectionHead"><h2>Една платформа.<br><em>Всички важни сигнали.</em></h2><p class="lead">BLIS™ не разглежда организацията като изолирана система. Пазарната среда, конкурентите, потребителското поведение, репутацията, дигиталното присъствие и външните фактори се анализират като взаимосвързана картина.</p></div><div id="solutions" class="capGrid"><article class="cap"><div class="capIco">◔</div><h3>Пазарна среда</h3><p>Тенденции, секторни промени, регулаторни и икономически фактори, нови практики и възможности.</p></article><article class="cap"><div class="capIco">♙</div><h3>Конкурентна среда</h3><p>Действия, инициативи, кампании, позициониране, нови продукти и сравнителен контекст.</p></article><article class="cap"><div class="capIco">◉</div><h3>Потребители</h3><p>Нагласи, обратна връзка, очаквания, въпроси, интерес и промени в поведението.</p></article><article class="cap"><div class="capIco">◇</div><h3>Репутация</h3><p>Медии, публичен тон, оценки, мнения и повтарящи се теми с потенциално влияние.</p></article><article class="cap"><div class="capIco">▣</div><h3>Дигитално присъствие</h3><p>Сайт, търсене, социални канали, съдържание, видимост и свързани публични сигнали.</p></article><article class="cap"><div class="capIco">✦</div><h3>Ранни сигнали</h3><p>Рискове, възможности, необичайни отклонения и фактори, които заслужават експертна проверка.</p></article></div></div></section>`

	fresh := `<section id="platform" class="blis-dark-platform">
<style>
.blis-dark-platform{padding:30px 0;background:#fff}
.blis-dark-shell{width:min(1420px,calc(100% - 32px));margin:auto;position:relative;overflow:hidden;border-radius:18px;padding:42px 34px;background:radial-gradient(circle at 78% 44%,rgba(0,116,255,.12),transparent 28%),radial-gradient(circle at 18% 78%,rgba(224,154,35,.11),transparent 25%),linear-gradient(135deg,#030813 0%,#06101f 48%,#020711 100%);border:1px solid #15253a;box-shadow:0 26px 70px rgba(4,12,27,.20);isolation:isolate}
.blis-dark-shell:before{content:"";position:absolute;width:640px;height:640px;right:-260px;top:-150px;border-radius:50%;background:repeating-radial-gradient(circle,rgba(26,133,255,.22) 0 1px,transparent 1px 28px);opacity:.40;animation:bdRotate 26s linear infinite;z-index:-1}
.blis-dark-shell:after{content:"";position:absolute;left:-8%;bottom:-42%;width:58%;height:76%;background:repeating-linear-gradient(8deg,transparent 0 12px,rgba(24,117,245,.28) 13px,transparent 14px 22px,rgba(218,145,24,.21) 23px,transparent 24px);transform:skewX(-18deg) rotate(-8deg);filter:blur(.2px);mask-image:linear-gradient(90deg,transparent,#000 26%,#000 72%,transparent);opacity:.62;animation:bdFlow 9s ease-in-out infinite alternate;z-index:-1}
.blis-dark-layout{display:grid;grid-template-columns:.78fr 1.72fr;gap:34px;align-items:stretch;position:relative;z-index:2}
.blis-dark-copy{padding:24px 8px 16px 4px;display:flex;flex-direction:column;justify-content:center}
.blis-dark-kicker{display:inline-flex;align-items:center;gap:8px;width:max-content;color:#e0a23a;font-size:9px;font-weight:850;letter-spacing:.15em;text-transform:uppercase;margin-bottom:15px}.blis-dark-kicker:before{content:"";width:7px;height:7px;border-radius:50%;background:#e3a331;box-shadow:0 0 18px #e3a331;animation:bdPulse 2.1s ease-in-out infinite}
.blis-dark-copy h2{font:500 clamp(40px,4.1vw,63px)/1.04 Georgia,serif;color:#f6f8fb;margin:0 0 20px;letter-spacing:-.025em}.blis-dark-copy h2 em{display:block;font-style:normal;color:#e3a331;margin-top:4px;text-shadow:0 0 26px rgba(227,163,49,.14)}
.blis-dark-copy p{max-width:420px;margin:0;color:#9baabd;font-size:14px;line-height:1.8}.blis-dark-scan{display:flex;align-items:center;gap:10px;margin-top:27px;color:#62758c;font-size:9px;font-weight:800;letter-spacing:.12em}.blis-dark-scan i{display:block;width:78px;height:1px;background:linear-gradient(90deg,#1588ff,transparent);position:relative}.blis-dark-scan i:after{content:"";position:absolute;top:-2px;left:0;width:5px;height:5px;border-radius:50%;background:#2b9cff;box-shadow:0 0 10px #2b9cff;animation:bdScan 2.8s linear infinite}
.blis-signal-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}
.blis-signal-card{position:relative;overflow:hidden;min-height:218px;padding:22px 20px 18px;border-radius:13px;background:linear-gradient(145deg,rgba(8,18,34,.96),rgba(4,10,21,.98));border:1px solid rgba(32,146,255,.72);box-shadow:inset 0 0 0 1px rgba(24,120,232,.08),0 0 22px rgba(0,119,255,.06);transition:transform .28s ease,border-color .28s ease,box-shadow .28s ease}
.blis-signal-card.gold{border-color:rgba(220,150,31,.78);box-shadow:inset 0 0 0 1px rgba(220,150,31,.07),0 0 22px rgba(220,150,31,.05)}
.blis-signal-card:hover{transform:translateY(-5px);border-color:#28a0ff;box-shadow:0 15px 38px rgba(0,108,230,.18),inset 0 0 34px rgba(0,111,255,.04)}.blis-signal-card.gold:hover{border-color:#e2a127;box-shadow:0 15px 38px rgba(215,145,29,.15),inset 0 0 34px rgba(215,145,29,.04)}
.blis-signal-card:before{content:"";position:absolute;left:-45%;top:-120%;width:36%;height:300%;background:linear-gradient(90deg,transparent,rgba(255,255,255,.07),transparent);transform:rotate(18deg);animation:bdSweep 8s ease-in-out infinite}
.blis-signal-card:nth-child(2):before,.blis-signal-card:nth-child(5):before{animation-delay:1.5s}.blis-signal-card:nth-child(3):before,.blis-signal-card:nth-child(6):before{animation-delay:3s}
.blis-signal-top{display:flex;gap:16px;align-items:flex-start}.blis-signal-icon{flex:0 0 62px;width:62px;height:62px;border-radius:50%;display:grid;place-items:center;color:#31a1ff;font-size:27px;border:1px solid rgba(42,151,255,.52);background:radial-gradient(circle,rgba(16,115,240,.18),rgba(2,9,20,.3) 58%,transparent 60%);box-shadow:0 0 0 8px rgba(25,124,235,.035),0 0 24px rgba(25,124,235,.16);position:relative;animation:bdIcon 4s ease-in-out infinite}.gold .blis-signal-icon{color:#e5a433;border-color:rgba(229,164,51,.50);background:radial-gradient(circle,rgba(222,147,28,.15),rgba(12,9,4,.3) 58%,transparent 60%);box-shadow:0 0 0 8px rgba(222,147,28,.035),0 0 24px rgba(222,147,28,.14)}
.blis-signal-icon:after{content:"";position:absolute;inset:-10px;border:1px dashed currentColor;border-radius:50%;opacity:.26;animation:bdRotate 12s linear infinite}
.blis-signal-body{min-width:0;padding-top:4px}.blis-signal-body h3{font-size:16px;line-height:1.28;color:#f5f8fc;margin:0 0 9px}.blis-signal-body p{font-size:11px;line-height:1.65;color:#8f9fb2;margin:0}
.blis-signal-foot{position:absolute;left:20px;right:20px;bottom:15px;display:flex;align-items:center;justify-content:space-between;color:#258ee9;font-size:8px;font-weight:850;letter-spacing:.12em;text-transform:uppercase}.gold .blis-signal-foot{color:#d89524}.blis-signal-foot span:last-child{display:flex;align-items:center;gap:7px}.blis-signal-foot b{width:5px;height:5px;border-radius:50%;background:currentColor;box-shadow:0 0 10px currentColor;animation:bdPulse 1.8s ease-in-out infinite}
@keyframes bdPulse{0%,100%{opacity:.45;transform:scale(.82)}50%{opacity:1;transform:scale(1.15)}}@keyframes bdRotate{to{transform:rotate(360deg)}}@keyframes bdScan{0%{left:0;opacity:0}10%{opacity:1}90%{opacity:1}100%{left:74px;opacity:0}}@keyframes bdSweep{0%,72%{left:-45%}100%{left:135%}}@keyframes bdFlow{from{transform:skewX(-18deg) rotate(-8deg) translateX(-2%)}to{transform:skewX(-18deg) rotate(-5deg) translateX(8%)}}@keyframes bdIcon{0%,100%{transform:translateY(0)}50%{transform:translateY(-3px)}}
@media(max-width:1120px){.blis-dark-layout{grid-template-columns:1fr}.blis-dark-copy{padding:5px 4px 10px}.blis-dark-copy p{max-width:760px}.blis-signal-card{min-height:205px}}
@media(max-width:820px){.blis-signal-grid{grid-template-columns:repeat(2,1fr)}.blis-dark-shell{padding:30px 22px}}
@media(max-width:560px){.blis-dark-platform{padding:18px 0}.blis-dark-shell{width:calc(100% - 20px);padding:28px 16px;border-radius:14px}.blis-dark-copy h2{font-size:39px}.blis-signal-grid{grid-template-columns:1fr}.blis-signal-card{min-height:190px}.blis-dark-shell:before{opacity:.2}}
@media(prefers-reduced-motion:reduce){.blis-dark-shell:before,.blis-dark-shell:after,.blis-signal-card:before,.blis-signal-icon,.blis-signal-icon:after,.blis-dark-kicker:before,.blis-dark-scan i:after,.blis-signal-foot b{animation:none!important}}
</style>
<div class="blis-dark-shell"><div class="blis-dark-layout"><div class="blis-dark-copy"><div class="blis-dark-kicker">BLIS Intelligence System</div><h2>Една платформа.<em>Всички важни сигнали.</em></h2><p>BLIS™ не разглежда организацията като изолирана система. Пазарната среда, конкурентите, потребителското поведение, репутацията, дигиталното присъствие и външните фактори се анализират като взаимосвързана картина.</p><div class="blis-dark-scan"><i></i><span>ПОСТОЯННО НАБЛЮДЕНИЕ</span></div></div><div id="solutions" class="blis-signal-grid">
<article class="blis-signal-card"><div class="blis-signal-top"><div class="blis-signal-icon">◔</div><div class="blis-signal-body"><h3>Пазарна среда</h3><p>Тенденции, секторни промени, регулаторни и икономически фактори, нови практики и възможности.</p></div></div><div class="blis-signal-foot"><span>SCANNING</span><span><b></b>ACTIVE</span></div></article>
<article class="blis-signal-card gold"><div class="blis-signal-top"><div class="blis-signal-icon">♙</div><div class="blis-signal-body"><h3>Конкурентна среда</h3><p>Действия, инициативи, кампании, позициониране, нови продукти и сравнителен контекст.</p></div></div><div class="blis-signal-foot"><span>SCANNING</span><span><b></b>ACTIVE</span></div></article>
<article class="blis-signal-card"><div class="blis-signal-top"><div class="blis-signal-icon">◎</div><div class="blis-signal-body"><h3>Потребители</h3><p>Нагласи, обратна връзка, очаквания, въпроси, интерес и промени в поведението.</p></div></div><div class="blis-signal-foot"><span>SCANNING</span><span><b></b>ACTIVE</span></div></article>
<article class="blis-signal-card gold"><div class="blis-signal-top"><div class="blis-signal-icon">◇</div><div class="blis-signal-body"><h3>Репутация</h3><p>Медии, публичен тон, оценки, мнения и повтарящи се теми с потенциално влияние.</p></div></div><div class="blis-signal-foot"><span>SCANNING</span><span><b></b>ACTIVE</span></div></article>
<article class="blis-signal-card"><div class="blis-signal-top"><div class="blis-signal-icon">▣</div><div class="blis-signal-body"><h3>Дигитално присъствие</h3><p>Сайт, търсене, социални канали, съдържание, видимост и свързани публични сигнали.</p></div></div><div class="blis-signal-foot"><span>SCANNING</span><span><b></b>ACTIVE</span></div></article>
<article class="blis-signal-card gold"><div class="blis-signal-top"><div class="blis-signal-icon">✦</div><div class="blis-signal-body"><h3>Ранни сигнали</h3><p>Рискове, възможности, необичайни отклонения и фактори, които заслужават експертна проверка.</p></div></div><div class="blis-signal-foot"><span>SCANNING</span><span><b></b>ACTIVE</span></div></article>
</div></div></div></section>`

	if strings.Contains(indexHTML, old) {
		indexHTML = strings.Replace(indexHTML, old, fresh, 1)
	}
}
