package main

import "bytes"

// KUB monitoring must never depend on a single external JS request or on the
// timing of the collector. This small inline bridge renders the verified
// same-day baseline immediately and then keeps the feed synchronized with the
// live signal API once per minute.
func init() {
	const script = `<script id="kub-monitoring-reliable-v1">
(function(){
'use strict';
if(!/\/kub-crisis\.html$/i.test(location.pathname))return;
const seeds=[
 {p:'2026-09-02T14:22:00+03:00',title:'Административният съд във Варна образува ново дело заради спирането на тока в „Баба Алино“',text:'Darik отразява новото дело по искане на „Форест клуб Варна“ ООД за незабавно възстановяване на тока и водата.',src:'DarikNews',url:'https://dariknews.bg/regioni/varna/administrativniiat-syd-vyv-varna-obrazuva-novo-delo-zaradi-spiraneto-na-toka-v-baba-alino-2465452',types:'institution utilities media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T14:09:00+03:00',title:'Административният съд във Варна образува ново дело заради спирането на тока в „Баба Алино“',text:'БТА съобщава за ново дело по искова молба на „Форест клуб Варна“ ООД за незабавно възстановяване на тока и водата.',src:'БТА',url:'https://www.bta.bg/',types:'institution utilities media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T13:43:00+03:00',title:'Собственици на имоти в „Баба Алино“ искат съдът да върне тока и водата',text:'Ново съдебно развитие: „Форест клуб Варна“ ООД е внесло искане до Административния съд – Варна за незабавно спиране на прекъсването на захранването.',src:'24 Пловдив',url:'https://www.24plovdiv.bg/novini/article/23492991',types:'institution utilities media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T13:39:00+03:00',title:'Събарят 23 незаконни обекта в „Баба Алино“, достъпът ще бъде ограничен',text:'Медийно разпространение на общинските действия за премахване и физическо ограничаване на достъпа.',src:'NewsPoint',url:'https://newspoint.bg/sabaryat-23-nezakonni-kasthi-v-baba-alino-dostapat-do-tyah-sthe-bade-ogranichen/',types:'institution media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T13:15:00+03:00',title:'Събарят 23 от къщите в „Баба Алино“, общината ограничава достъпа',text:'Публикация за 19 издадени и 4 предстоящи заповеди и мерките за ограничаване на достъпа.',src:'TrafficNews',url:'https://trafficnews.bg/bulgaria/sabariat-23-kashtite-baba-alino-obshtinata-ogranichava-388040/',types:'institution media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T12:52:00+03:00',title:'23 обекта в „Баба Алино“ отиват към премахване, общината ще ограничи достъпа',text:'Материалът съобщава за 19 издадени и още 4 подготвяни заповеди за премахване, както и за последващо ограничаване на физическия достъп.',src:'24 часа',url:'https://www.24chasa.bg/index.php/bulgaria/article/23492303',types:'institution media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T12:21:00+03:00',title:'Запечатват със стикери и ленти сградите в „Баба Алино“',text:'Публикация за 19 издадени заповеди за премахване, още 4 предстоящи и планирано физическо ограничаване на достъпа до обектите.',src:'Варна Утре',url:'https://varnautre.bg/2026/09/02/652846-zapechatvat_sus_stikeri_i_lenti_nezakonnite_sgradi_v_baba_alino_vuv_varna',types:'institution media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T10:58:00+03:00',title:'„Възраждане“: Действията на КУБ са описвани и в доклади на ДАНС',text:'Focus публикува разширено отразяване на декларацията с твърдения за доклади на ДАНС и информираност на държавните институции.',src:'Focus News',url:'https://www.focus-news.net/novini/regioni/Vuzrazhdane-za-Baba-Alino-Deistviyata-na-grupirovkata-KUB-sa-opisvani-i-v-dokladi-na-DANS-Nikoi-na-nai-visok-durzhaven-post-ne-mozhe-da-kazhe-ne-znaeh--3019129',types:'institution media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T10:50:00+03:00',title:'Съдът реши: Спирането на тока в „Баба Алино“ остава в сила',text:'Публикация за съдебния отказ за незабавно възстановяване на електрозахранването към обекти на „Форест клуб Варна“.',src:'Днес+',url:'https://dnesplus.bg/varna/sadat-reshi-spiraneto-na-toka-v-baba-alino-ostava-v-sila_1233756',types:'institution utilities media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T10:49:00+03:00',title:'„Възраждане“ пита: Има ли политически чадър над КУБ и Олег Невзоров',text:'Darik отразява декларацията на Коста Стоянов и твърденията за институционален чадър над КУБ.',src:'DarikNews',url:'https://dariknews.bg/novini/bylgariia/vyzrazhdane-pita-ima-li-politicheski-chadyr-nad-ukrainskata-grupirovka-kub-i-oleg-nevzorov-2465416',types:'institution media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T10:31:00+03:00',title:'Евроком: Строителството в „Баба Алино“ продължава, токът не е напълно спрян',text:'Нов медиен сигнал за продължаващи строителни дейности, електрозахранване и критики към институционалните действия около „Баба Алино“.',src:'Евроком',url:'https://eurocom.bg/video/nezakonnoto-selishte-baba-alino-stroitelstvoto-prodalzhava-tokat-ne-e-napalno-spryan/',types:'institution utilities media kub',sev:'КРИТИЧЕН'}
];
function esc(s){return String(s||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]});}
function clean(s){return String(s||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function dateHTML(raw){const d=new Date(raw);if(isNaN(d.getTime()))return esc(raw||'LIVE');return d.toLocaleDateString('bg-BG',{day:'2-digit',month:'2-digit',year:'numeric'})+'<br>'+d.toLocaleTimeString('bg-BG',{hour:'2-digit',minute:'2-digit'});}
function types(s){const low=(String(s.title||'')+' '+String(s.text||'')).toLowerCase();const out=['media'];if(/куб|корпорац|forest club|форест клуб/.test(low))out.push('kub');if(/съд|прокурат|парламент|народното събрание|община|полици|министер|данс|строителен контрол/.test(low))out.push('institution');if(/ток|електро|вод|виК|вик|електрозахран|водоснабд/.test(low))out.push('utilities');return Array.from(new Set(out)).join(' ');}
function severity(s){const v=String(s.severity||'').toLowerCase();return v==='critical'?'КРИТИЧЕН':v==='high'?'ВИСОК':v==='medium'?'СРЕДЕН':'СИГНАЛ';}
function status(text,bad){const filters=document.querySelector('#monitoring .filters');if(!filters)return;let el=document.getElementById('kubReliableLiveStatus');if(!el){el=document.createElement('span');el.id='kubReliableLiveStatus';el.className='filter';el.style.marginLeft='auto';el.style.cursor='default';filters.appendChild(el);}el.textContent=text;el.style.borderColor=bad?'#e0aaaa':'';el.style.color=bad?'#a33':'';}
function render(rows,kind){const feed=document.getElementById('feed');if(!feed||!Array.isArray(rows))return 0;const links=new Set(Array.from(feed.querySelectorAll('.item a[href]')).map(function(a){return a.href;}));const titles=new Set(Array.from(feed.querySelectorAll('.item h3')).map(function(h){return clean(h.textContent).toLowerCase();}));const sorted=rows.slice().sort(function(a,b){return new Date(b.p||b.published_at||b.detected_at||0)-new Date(a.p||a.published_at||a.detected_at||0);});const made=[];for(const r of sorted){const title=clean(r.title);if(!title)continue;let href='';try{href=new URL(r.url,location.origin).href}catch(_){href=String(r.url||'');}const key=title.toLowerCase();if((href&&links.has(href))||titles.has(key))continue;links.add(href);titles.add(key);const a=document.createElement('article');a.className='item';a.dataset.type=r.types||types(r);a.dataset.text=clean(title+' '+(r.text||'')+' '+(r.src||r.source||''));const src=r.src||r.source||'външен източник';const sev=r.sev||severity(r);a.innerHTML='<time>'+dateHTML(r.p||r.published_at||r.detected_at)+'</time><div><h3>'+esc(title)+'</h3><p>'+esc(clean(r.text||title)).slice(0,900)+'</p><div class="meta"><span>'+esc(kind)+'</span><span>'+esc(src)+'</span><span>'+esc(sev)+'</span></div></div>'+(href?'<a target="_blank" rel="noopener" href="'+esc(href)+'">ИЗТОЧНИК ↗</a>':'');made.push(a);if(made.length>=100)break;}for(let i=made.length-1;i>=0;i--)feed.prepend(made[i]);try{if(Array.isArray(items))made.forEach(function(x){items.unshift(x);});}catch(_){ }try{if(typeof filterFeed==='function')filterFeed();}catch(_){ }return made.length;}
async function sync(){try{const res=await fetch('/api/signals?client=kub&limit=250&_='+Date.now(),{cache:'no-store'});if(!res.ok)throw new Error(String(res.status));const data=await res.json();render(data.signals||[],'LIVE СИГНАЛ');const d=new Date(data.updated_at||Date.now());const t=isNaN(d.getTime())?'':d.toLocaleTimeString('bg-BG',{hour:'2-digit',minute:'2-digit'});status('LIVE МОНИТОРИНГ'+(t?' · '+t:''),false);}catch(e){status('LIVE МОНИТОРИНГ · НЯМА ВРЪЗКА',true);}}
function boot(){render(seeds,'ТЕКУЩ СИГНАЛ');status('LIVE МОНИТОРИНГ · СИНХРОНИЗИРАНЕ…',false);sync();setTimeout(function(){render(seeds,'ТЕКУЩ СИГНАЛ');sync();},700);setInterval(sync,60000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
</script>`
	if !bytes.Contains(blisI18NScripts, []byte(`id="kub-monitoring-reliable-v1"`)) {
		blisI18NScripts = append([]byte(script), blisI18NScripts...)
	}
}
