package main

import "bytes"

// KUB monitoring gets one canonical writer. It renders the latest verified
// same-day publications, keeps the live collector synchronized and always
// sorts the visible feed by publication time (newest first).
func init() {
	const script = `<script id="kub-monitoring-reliable-v2">
(function(){
'use strict';
if(!/\/kub-crisis\.html$/i.test(location.pathname))return;
const seeds=[
 {p:'2026-09-02T14:22:00+03:00',title:'Административният съд във Варна образува ново дело заради спирането на тока в „Баба Алино“',text:'DarikNews отразява новото дело по искане на „Форест клуб Варна“ ООД за незабавно възстановяване на тока и водата.',src:'DarikNews',url:'https://dariknews.bg/regioni/varna/administrativniiat-syd-vyv-varna-obrazuva-novo-delo-zaradi-spiraneto-na-toka-v-baba-alino-2465452',types:'institution utilities media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T14:09:00+03:00',title:'Административният съд във Варна образува ново дело заради спирането на тока в местността Баба Алино',text:'БТА съобщава за ново дело по искова молба на „Форест клуб Варна“ ООД за незабавно възстановяване на тока и водата.',src:'БТА',url:'https://www.bta.bg/',types:'institution utilities media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T13:43:00+03:00',title:'Собственици на имоти в „Баба Алино“ искат съдът да върне тока и водата',text:'„Форест Клуб Варна“ ООД е внесло ново искане до Административния съд – Варна за незабавно спиране на прекъсването на захранването.',src:'24 часа',url:'https://www.24chasa.bg/index.php/bulgaria/article/23492943',types:'institution utilities media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T13:35:00+03:00',title:'Отново настояват токът и водата на имоти в Баба Алино да бъдат възстановени',text:'Радио Варна съобщава за новото дело на „Форест Клуб Варна“ и искането за спиране на действията по прекъсване на електрозахранването и водоподаването.',src:'БНР · Радио Варна',url:'https://bnrnews.bg/varna/post/523239/otnovo-nastoyavat-tokat-i-vodata-na-imoti-v-baba-alino-da-badat-vazstanoveni',types:'institution utilities media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T12:52:00+03:00',title:'23 незаконни къщи в Баба Алино отиват към премахване, общината ще ограничи достъпа до тях',text:'Материалът съобщава за 19 издадени и още 4 подготвяни заповеди за премахване, както и за последващо ограничаване на физическия достъп.',src:'24 часа',url:'https://www.24chasa.bg/index.php/bulgaria/article/23492303',types:'institution media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T12:21:00+03:00',title:'Запечатват със стикери и ленти незаконните сгради в „Баба Алино“ във Варна',text:'Публикация за 19 издадени заповеди за премахване, още 4 предстоящи и планирано физическо ограничаване на достъпа до обектите.',src:'Варна Утре',url:'https://varnautre.bg/2026/09/02/652846-zapechatvat_sus_stikeri_i_lenti_nezakonnite_sgradi_v_baba_alino_vuv_varna',types:'institution media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T10:58:00+03:00',title:'„Възраждане“: Действията на КУБ са описвани и в доклади на ДАНС',text:'Focus публикува разширено отразяване на декларацията с твърдения за доклади на ДАНС и информираност на държавните институции.',src:'Focus News',url:'https://www.focus-news.net/novini/regioni/Vuzrazhdane-za-Baba-Alino-Deistviyata-na-grupirovkata-KUB-sa-opisvani-i-v-dokladi-na-DANS-Nikoi-na-nai-visok-durzhaven-post-ne-mozhe-da-kazhe-ne-znaeh--3019129',types:'institution media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T10:50:00+03:00',title:'Съдът реши: Спирането на тока в Баба Алино остава в сила',text:'Днес+ съобщава за съдебния отказ за незабавно възстановяване на електрозахранването към обекти на „Форест клуб Варна“.',src:'Днес+',url:'https://dnesplus.bg/varna/sadat-reshi-spiraneto-na-toka-v-baba-alino-ostava-v-sila_1233756',types:'institution utilities media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T10:49:00+03:00',title:'„Възраждане“ пита: Има ли политически чадър над КУБ и Олег Невзоров',text:'DarikNews отразява декларацията на Коста Стоянов и твърденията за институционален чадър над КУБ.',src:'DarikNews',url:'https://dariknews.bg/novini/bylgariia/vyzrazhdane-pita-ima-li-politicheski-chadyr-nad-ukrainskata-grupirovka-kub-i-oleg-nevzorov-2465416',types:'institution media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T10:31:00+03:00',title:'Евроком: Строителството в „Баба Алино“ продължава, токът не е напълно спрян',text:'Нов медиен сигнал за продължаващи строителни дейности, електрозахранване и критики към институционалните действия около „Баба Алино“.',src:'Евроком',url:'https://eurocom.bg/video/nezakonnoto-selishte-baba-alino-stroitelstvoto-prodalzhava-tokat-ne-e-napalno-spryan/',types:'institution utilities media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T10:03:00+03:00',title:'Коста Стоянов за „Баба Алино“: Държавата знае, въпросът е защо не действа',text:'БТА публикува политическата декларация от парламентарната трибуна на Народното събрание по казуса „Баба Алино“.',src:'БТА',url:'https://www.bta.bg/bg/news/bulgaria/oficial-messages/1196415-kosta-stoyanov-za-nay-golyamata-koruptsionna-shema-baba-alino-darzhavata-znae',types:'institution media kub',sev:'КРИТИЧЕН'},
 {p:'2026-09-02T09:58:00+03:00',title:'БНТ: Коста Стоянов с декларация в парламента за „Баба Алино“',text:'БНТ отразява декларацията и критиките за продължително институционално бездействие по казуса.',src:'БНТ',url:'https://bntnews.bg/news/kosta-stoyanov-za-nai-golyamata-korupcionna-shema-baba-alino-darzhavata-znae-vaprosat-e-zashto-ne-deistva-1410513news.html',types:'institution media kub',sev:'КРИТИЧЕН'}
];
function esc(s){return String(s||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]});}
function clean(s){return String(s||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function stamp(raw){const d=new Date(raw);return isNaN(d.getTime())?0:d.getTime();}
function dateHTML(raw){const d=new Date(raw);if(isNaN(d.getTime()))return esc(raw||'LIVE');return d.toLocaleDateString('bg-BG',{day:'2-digit',month:'2-digit',year:'numeric'})+'<br>'+d.toLocaleTimeString('bg-BG',{hour:'2-digit',minute:'2-digit'});}
function inferTypes(s){const low=(String(s.title||'')+' '+String(s.text||'')).toLowerCase();const out=['media'];if(/куб|корпорац|forest club|форест клуб/.test(low))out.push('kub');if(/съд|прокурат|парламент|народното събрание|община|полици|министер|данс|строителен контрол/.test(low))out.push('institution');if(/ток|електро|вод|вик|електрозахран|водоснабд/.test(low))out.push('utilities');return Array.from(new Set(out)).join(' ');}
function severity(s){const v=String(s.severity||'').toLowerCase();return v==='critical'?'КРИТИЧЕН':v==='high'?'ВИСОК':v==='medium'?'СРЕДЕН':'СИГНАЛ';}
function status(text,bad){const filters=document.querySelector('#monitoring .filters');if(!filters)return;let el=document.getElementById('kubReliableLiveStatus');if(!el){el=document.createElement('span');el.id='kubReliableLiveStatus';el.className='filter';el.style.marginLeft='auto';el.style.cursor='default';filters.appendChild(el);}el.textContent=text;el.style.borderColor=bad?'#e0aaaa':'';el.style.color=bad?'#a33':'';}
function oldItemStamp(el){if(el.dataset.published)return Number(el.dataset.published)||0;const txt=(el.querySelector('time')||{}).innerText||'';const m=txt.match(/(\d{2})\.(\d{2})\.(\d{4})(?:\s+|\n)?(\d{2}):(\d{2})/);if(!m)return 0;return new Date(Number(m[3]),Number(m[2])-1,Number(m[1]),Number(m[4]),Number(m[5])).getTime();}
function sortFeed(){const feed=document.getElementById('feed');if(!feed)return;const rows=Array.from(feed.querySelectorAll('.item'));rows.sort(function(a,b){return oldItemStamp(b)-oldItemStamp(a);});rows.forEach(function(x){feed.appendChild(x);});}
function dynamicFilter(){const feed=document.getElementById('feed'),search=document.getElementById('feedSearch');if(!feed)return;const active=document.querySelector('#monitoring .filter.active[data-filter]');const f=active?active.dataset.filter:'all';const term=((search&&search.value)||'').trim().toLowerCase();feed.querySelectorAll('.item').forEach(function(x){const okType=f==='all'||(x.dataset.type||'').split(' ').includes(f);const hay=(x.innerText+' '+(x.dataset.text||'')).toLowerCase();x.classList.toggle('hidden',!(okType&&(!term||hay.includes(term))));});}
function render(rows,kind){const feed=document.getElementById('feed');if(!feed||!Array.isArray(rows))return 0;const links=new Set(Array.from(feed.querySelectorAll('.item a[href]')).map(function(a){return a.href;}));const made=[];for(const r of rows){const title=clean(r.title);if(!title)continue;let href='';try{href=new URL(r.url,location.origin).href}catch(_){href=String(r.url||'');}if(href&&links.has(href))continue;if(href)links.add(href);const published=r.p||r.published_at||r.detected_at||'';const a=document.createElement('article');a.className='item';a.dataset.type=r.types||inferTypes(r);a.dataset.text=clean(title+' '+(r.text||'')+' '+(r.src||r.source||''));a.dataset.published=String(stamp(published));const src=r.src||r.source||'външен източник';const sev=r.sev||severity(r);a.innerHTML='<time>'+dateHTML(published)+'</time><div><h3>'+esc(title)+'</h3><p>'+esc(clean(r.text||title)).slice(0,900)+'</p><div class="meta"><span>'+esc(kind)+'</span><span>'+esc(src)+'</span><span>'+esc(sev)+'</span></div></div>'+(href?'<a target="_blank" rel="noopener" href="'+esc(href)+'">ИЗТОЧНИК ↗</a>':'');feed.appendChild(a);made.push(a);if(made.length>=150)break;}sortFeed();dynamicFilter();return made.length;}
async function sync(){try{const res=await fetch('/api/signals?client=kub&limit=250&_='+Date.now(),{cache:'no-store'});if(!res.ok)throw new Error(String(res.status));const data=await res.json();render(data.signals||[],'LIVE СИГНАЛ');const d=new Date(data.updated_at||Date.now());const t=isNaN(d.getTime())?'':d.toLocaleTimeString('bg-BG',{hour:'2-digit',minute:'2-digit'});status('LIVE МОНИТОРИНГ'+(t?' · '+t:''),false);}catch(e){status('LIVE МОНИТОРИНГ · НЯМА ВРЪЗКА',true);}sortFeed();dynamicFilter();}
function bindDynamicFilters(){const search=document.getElementById('feedSearch');if(search)search.addEventListener('input',function(){setTimeout(dynamicFilter,0);});document.querySelectorAll('#monitoring .filter[data-filter]').forEach(function(b){b.addEventListener('click',function(){setTimeout(dynamicFilter,0);});});}
function boot(){render(seeds,'ТЕКУЩ СИГНАЛ');sortFeed();bindDynamicFilters();status('LIVE МОНИТОРИНГ · СИНХРОНИЗИРАНЕ…',false);sync();setTimeout(function(){render(seeds,'ТЕКУЩ СИГНАЛ');sortFeed();sync();},900);setInterval(sync,60000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
</script>`
	if !bytes.Contains(blisI18NScripts, []byte(`id="kub-monitoring-reliable-v2"`)) {
		blisI18NScripts = append([]byte(script), blisI18NScripts...)
	}
}
