package main

import (
	"math"
	"sort"
	"strings"
	"time"
)

type MetricChangeV33 struct{
	Source string `json:"source"`; Metric string `json:"metric"`; Current float64 `json:"current"`; Previous float64 `json:"previous"`; Delta float64 `json:"delta"`; ChangePct float64 `json:"change_pct"`; Direction string `json:"direction"`; Importance float64 `json:"importance"`; ObservedAt string `json:"observed_at"`; PreviousAt string `json:"previous_at"`; Interpretation string `json:"interpretation"`
}
type SnapshotTrendV33 struct{Metric string `json:"metric"`;Current float64 `json:"current"`;Previous float64 `json:"previous"`;Delta float64 `json:"delta"`;ChangePct float64 `json:"change_pct"`;CurrentAt string `json:"current_at"`;PreviousAt string `json:"previous_at"`}

type metricPairV33 struct{cur,prev Observation;hasCur,hasPrev bool}
func ignoreMetricV33(source,metric string)bool{if source=="signal_collector"||source=="competitor_change_tracker"{return true};m:=strings.ToLower(metric);for _,x:=range []string{"response_ms","title","url","error","signal_event_","checked_at"}{if strings.Contains(m,x){return true}};return false}
func numericObsV33(v interface{})(float64,bool){x:=f(v);switch v.(type){case float64,int,jsonNumberAliasV33:return x,true};return x,x!=0}
type jsonNumberAliasV33 interface{}
func metricImportanceV33(metric string,cur,prev,delta,pct float64)float64{m:=strings.ToLower(metric);a:=math.Abs(delta);p:=math.Abs(pct);switch{case strings.Contains(m,"reachable")||strings.Contains(m,"active"):if cur!=prev{return 100};return 0;case strings.Contains(m,"rating")&&!strings.Contains(m,"ratings"):return clampV3(a*180+p*.3);case strings.Contains(m,"score")||strings.Contains(m,"index")||strings.Contains(m,"confidence"):return clampV3(a*8+p*.35);case strings.Contains(m,"reviews")||strings.Contains(m,"ratings")||strings.Contains(m,"mentions")||strings.Contains(m,"posts")||strings.Contains(m,"followers")||strings.Contains(m,"activity"):return clampV3(p*.75+math.Min(25,a*.12));case strings.Contains(m,"price"):return clampV3(p*.85);case strings.Contains(m,"category")||strings.Contains(m,"portfolio")||strings.Contains(m,"content")||strings.Contains(m,"page_words"):return clampV3(p*.6+math.Min(30,a*.08));default:return clampV3(p*.55+math.Min(35,a*.3))}}
func metricDirectionV33(metric string,delta float64)string{if math.Abs(delta)<0.000001{return "stable"};m:=strings.ToLower(metric);negativeWhenUp:=strings.Contains(m,"risk")||strings.Contains(m,"negative")||strings.Contains(m,"failed")||strings.Contains(m,"response_ms");if delta>0{if negativeWhenUp{return "worse"};return "better"};if negativeWhenUp{return "better"};return "worse"}
func metricInterpretationV33(source,metric,dir string,cur,prev float64)string{m:=strings.ToLower(metric);label:=metric;if strings.Contains(m,"rating"){label="публичната оценка"}else if strings.Contains(m,"review"){label="обемът на отзивите"}else if strings.Contains(m,"mention"){label="обемът на споменаванията"}else if strings.Contains(m,"activity"){label="видимата активност"}else if strings.Contains(m,"category")||strings.Contains(m,"portfolio"){label="продуктовото/категорийното покритие"}else if strings.Contains(m,"score")||strings.Contains(m,"index"){label="измереният индекс/score"}else if strings.Contains(m,"reachable")||strings.Contains(m,"active"){label="достъпността на източника"};verb:=map[string]string{"better":"се подобрява","worse":"се влошава","stable":"остава без съществена промяна"}[dir];return source+": "+label+" "+verb+" ("+formatScoreOrNumberV33(prev)+" → "+formatScoreOrNumberV33(cur)+")."}
func formatScoreOrNumberV33(v float64)string{if math.Abs(v-math.Round(v))<0.01{return strconvItoaV3(int(math.Round(v)))};whole:=math.Round(v*100)/100;s:=strconvItoaV3(int(math.Abs(whole)));frac:=int(math.Round((math.Abs(whole)-math.Floor(math.Abs(whole)))*100));if frac==0{return s};if whole<0{s="-"+s};if frac%10==0{return s+"."+strconvItoaV3(frac/10)};return s+"."+func()string{if frac<10{return "0"+strconvItoaV3(frac)};return strconvItoaV3(frac)}()}
func metricChangesV33(c *Client)[]MetricChangeV33{pairs:=map[string]*metricPairV33{};for i:=len(c.Observations)-1;i>=0;i--{o:=c.Observations[i];if ignoreMetricV33(o.SourceKey,o.MetricKey){continue};key:=o.SourceKey+"|"+o.MetricKey;p:=pairs[key];if p==nil{p=&metricPairV33{};pairs[key]=p};if !p.hasCur{if _,ok:=numericObsV33(o.Value);ok{p.cur=o;p.hasCur=true};continue};if !p.hasPrev{if _,ok:=numericObsV33(o.Value);ok{p.prev=o;p.hasPrev=true}}}
	out:=[]MetricChangeV33{};for key,p:=range pairs{if !p.hasCur||!p.hasPrev{continue};cur,ok1:=numericObsV33(p.cur.Value);prev,ok2:=numericObsV33(p.prev.Value);if !ok1||!ok2{continue};delta:=cur-prev;pct:=0.0;if math.Abs(prev)>0.000001{pct=delta/math.Abs(prev)*100}else if math.Abs(cur)>0.000001{pct=100};imp:=metricImportanceV33(p.cur.MetricKey,cur,prev,delta,pct);if imp<18{continue};parts:=strings.SplitN(key,"|",2);dir:=metricDirectionV33(parts[1],delta);out=append(out,MetricChangeV33{Source:parts[0],Metric:parts[1],Current:cur,Previous:prev,Delta:math.Round(delta*100)/100,ChangePct:math.Round(pct*10)/10,Direction:dir,Importance:imp,ObservedAt:p.cur.ObservedAt,PreviousAt:p.prev.ObservedAt,Interpretation:metricInterpretationV33(parts[0],parts[1],dir,cur,prev)})};sort.SliceStable(out,func(i,j int)bool{if out[i].Importance!=out[j].Importance{return out[i].Importance>out[j].Importance};return out[i].ObservedAt>out[j].ObservedAt});if len(out)>30{out=out[:30]};return out}
func snapshotNumberV33(p map[string]interface{},key string)(float64,bool){v,ok:=p[key];if !ok{return 0,false};x:=f(v);switch v.(type){case float64,int:return x,true};return x,x!=0}
func snapshotTrendsV33(c *Client)[]SnapshotTrendV33{if len(c.Snapshots)<2{return nil};cur:=c.Snapshots[len(c.Snapshots)-1];prev:=c.Snapshots[len(c.Snapshots)-2];keys:=[]string{"blis_index","benchmark","confidence","trend"};out:=[]SnapshotTrendV33{};for _,k:=range keys{a,ok1:=snapshotNumberV33(cur.Payload,k);b,ok2:=snapshotNumberV33(prev.Payload,k);if !ok1||!ok2{continue};delta:=a-b;pct:=0.0;if math.Abs(b)>0.0001{pct=delta/math.Abs(b)*100};out=append(out,SnapshotTrendV33{Metric:k,Current:a,Previous:b,Delta:math.Round(delta*100)/100,ChangePct:math.Round(pct*10)/10,CurrentAt:cur.CreatedAt,PreviousAt:prev.CreatedAt})};return out}
func buildMetricIntelligenceV33(slug string)map[string]interface{}{c:=analysisClientCopyV3(slug);if c==nil{return map[string]interface{}{"version":"3.3","client":slug,"error":"client not found"}};changes:=metricChangesV33(c);snap:=snapshotTrendsV33(c);better,worse:=0,0;for _,x:=range changes{if x.Direction=="better"{better++};if x.Direction=="worse"{worse++}};status:="Стабилни измерени показатели";if worse>=3&&worse>better{status="Натрупване на влошаващи се показатели"}else if better>=3&&better>worse{status="Измеримо подобрение по няколко показателя"}else if len(changes)>0{status="Смесена динамика по измерените показатели"};return map[string]interface{}{"version":"3.3","client":slug,"client_name":c.Name,"generated_at":nowISO(),"status":status,"changes":changes,"snapshot_trends":snap,"summary":map[string]interface{}{"significant_changes":len(changes),"improving":better,"worsening":worse,"snapshots":len(c.Snapshots),"observations":len(c.Observations)},"method":map[string]interface{}{"uses_measured_observations":true,"compares_latest_two_values":true,"importance_by_metric_type":true,"response_time_excluded":true,"signal_events_excluded":true}}}
func init(){_ = time.RFC3339}
