package main

import "strings"

func init() {
	oldNav := `<nav class="nav"><a href="#platform">Платформа</a><a href="#solutions">Решения</a><a href="/methodology.html">Методология</a><a href="#resources">Ресурси</a><a href="#clients">Проекти</a><a href="/brand-lab.html">За Brand Lab</a></nav>`
	newNav := `<nav class="nav"><a href="#platform">Платформа</a><a href="#solutions">Решения</a><a href="/methodology.html">Методология</a><div class="hubNav"><a class="hubNavTrigger" href="/intelligence-hub.html">Intelligence Hub <span>▾</span></a><div class="hubNavMenu"><a href="/intelligence-hub.html"><b>Всички материали</b><small>Начална страница на Hub-а</small></a><a href="/intelligence-retail-bulgaria-2026.html"><b>Пазари</b><small>Market & Sector Intelligence</small></a><a href="/intelligence-reputation-trust.html"><b>Репутация</b><small>Reputation Intelligence</small></a><a href="/intelligence-hub.html#competitive"><b>Конкуренти</b><small>Competitive Intelligence</small></a><a href="/intelligence-ai-search.html"><b>Дигитална среда</b><small>Digital & AI Intelligence</small></a><a href="/methodology.html"><b>Методология</b><small>Data, sources & confidence</small></a><a href="/intelligence-calendar.html"><b>Редакционен календар</b><small>12-месечен план</small></a></div></div><a href="#clients">Проекти</a><a href="/brand-lab.html">За Brand Lab</a></nav>`
	if strings.Contains(indexHTML, oldNav) {
		indexHTML = strings.Replace(indexHTML, oldNav, newNav, 1)
	}

	oldHub := `<section id="resources" class="section soft"><div class="container"><div class="sectionHead"><h2>Intelligence <em>Hub</em></h2><p class="lead">Публична библиотека от методология, анализи, секторни наблюдения, новини и практически ресурси. Целта е BLIS Navigator да бъде полезен информационен портал, а не само вход към dashboard.</p></div><div class="hubGrid"><a class="article" href="#"><span class="tag">Анализ</span><span class="date">август 2026</span><h3>Кои промени в потребителската среда заслужават внимание през второто полугодие</h3><span>Прочети повече →</span></a><a class="article" href="#"><span class="tag">Пазар</span><span class="date">август 2026</span><h3>Конкурентни движения: кога единичният сигнал се превръща в тенденция</h3><span>Прочети повече →</span></a><a class="article" href="/methodology.html"><span class="tag">Методология</span><span class="date">BLIS</span><h3>Как BLIS оценява значимостта, надеждността и практическата приложимост на информацията</h3><span>Научи повече →</span></a><a class="article" href="#"><span class="tag">Ресурс</span><span class="date">BLIS</span><h3>От информационен шум към аналитичен контекст и управленско знание</h3><span>Прочети повече →</span></a></div></div></section>`

	newHub := `<section id="resources" class="section soft homeHubLive"><style>
.hubNav{position:relative;display:flex;align-items:center;height:88px}.hubNavTrigger{display:flex!important;align-items:center;gap:6px;color:#b77b19!important;line-height:1}.hubNavTrigger span{display:inline-block;font-size:11px;line-height:1;position:static;transform:none!important}.hubNavMenu{position:absolute;top:66px;left:50%;transform:translateX(-50%) translateY(8px);width:330px;padding:10px;background:rgba(255,255,255,.99);border:1px solid #dce3eb;border-radius:14px;box-shadow:0 22px 55px rgba(20,40,64,.16);opacity:0;visibility:hidden;pointer-events:none;transition:.18s;z-index:300}.hubNav:hover .hubNavMenu,.hubNav:focus-within .hubNavMenu{opacity:1;visibility:visible;pointer-events:auto;transform:translateX(-50%) translateY(0)}.hubNavMenu a{display:block!important;padding:10px 12px!important;border-radius:9px!important;color:#25384f!important}.hubNavMenu a:hover{background:#f7f9fc;color:#a96f11!important}.hubNavMenu b{display:block;font-size:12px}.hubNavMenu small{display:block;margin-top:3px;color:#7d8998;font-size:9px;font-weight:500}
.homeHubLive{position:relative;overflow:hidden;padding:52px 0!important}.homeHubLive:before{display:none!important}.homeHubTop{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:end;gap:34px;margin-bottom:22px}.homeHubTop .sectionHead{display:block!important;margin:0!important;min-width:0}.homeHubTop .sectionHead h2{min-width:0!important;margin:0 0 14px!important}.homeHubTop .sectionHead .lead{max-width:820px!important;margin:0!important}.hubAll{white-space:nowrap;position:relative;z-index:2;align-self:end}.homeHubKinds{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 20px}.homeHubKinds a{text-decoration:none;padding:8px 11px;border:1px solid #dce3eb;border-radius:999px;background:#fff;color:#536176;font-size:10px;font-weight:750}.homeHubKinds a:hover{border-color:#d6a14b;color:#9d6915}.homeHubLive .hubGrid{grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.homeHubLive .article{min-height:218px;display:flex;flex-direction:column;position:relative;overflow:hidden}.homeHubLive .article:before{content:"";height:4px;position:absolute;left:0;right:0;top:0;background:linear-gradient(90deg,#213e60,#c58a24)}.homeHubLive .article h3{font:500 21px/1.28 Georgia,serif;color:#17304d;margin:22px 0 14px}.homeHubLive .article p{font-size:11px;line-height:1.6;color:#6d7b8d;margin:0 0 16px}.homeHubLive .article .read{margin-top:auto;color:#b47617;font-size:11px;font-weight:800}.homeHubMeta{display:flex;justify-content:space-between;gap:12px}.homeHubLive .date{float:none}.hubPulse{display:inline-flex;align-items:center;gap:6px;color:#2ba769;font-size:9px;font-weight:800}.hubPulse i{width:6px;height:6px;border-radius:50%;background:#2ba769;box-shadow:0 0 0 5px rgba(43,167,105,.08)}
@media(max-width:1100px){.hubNav{height:auto}.hubNavMenu{display:none}.homeHubLive{padding:48px 0!important}.homeHubTop{grid-template-columns:1fr;gap:16px}.hubAll{justify-self:start}.homeHubLive .hubGrid{grid-template-columns:1fr 1fr}}
@media(max-width:720px){.homeHubLive{padding:40px 0!important}.homeHubLive .hubGrid{grid-template-columns:1fr}.homeHubKinds{gap:6px;margin-bottom:14px}.homeHubKinds a{font-size:9px}.homeHubLive .article{min-height:205px}}
</style><div class="container"><div class="homeHubTop"><div class="sectionHead"><h2>Intelligence <em>Hub</em></h2><p class="lead">Аналитичен център на BLIS за реални пазарни данни, репутационни и конкурентни сигнали, секторни наблюдения, казуси и методология. Всеки материал свързва данните с контекст и практическо значение.</p></div><a class="btn hubAll" href="/intelligence-hub.html">Виж целия Hub →</a></div><div class="homeHubKinds"><a href="/intelligence-hub.html">Всички</a><a href="/intelligence-retail-bulgaria-2026.html">Пазари</a><a href="/intelligence-reputation-trust.html">Репутация</a><a href="/intelligence-hub.html#competitive">Конкуренти</a><a href="/intelligence-ai-search.html">Digital & AI</a><a href="/methodology.html">Методология</a><a href="/intelligence-calendar.html">Календар</a></div><div class="hubGrid"><a class="article" href="/intelligence-retail-bulgaria-2026.html"><div class="homeHubMeta"><span class="tag">Market Intelligence</span><span class="hubPulse"><i></i> Публикувано</span></div><h3>Retail Intelligence: България 2026 — растеж, но под висока несигурност</h3><p>НСИ, Eurostat, CBRE/Forton, онлайн търговия, retail parks и реален секторен казус.</p><span class="read">Прочети анализа →</span></a><a class="article" href="/intelligence-reputation-trust.html"><div class="homeHubMeta"><span class="tag">Reputation Intelligence</span><span class="hubPulse"><i></i> Публикувано</span></div><h3>Репутацията не е рейтинг: доверието вече е фактор при покупката</h3><p>Как trust, reviews и публичният контекст променят оценката на една марка.</p><span class="read">Прочети анализа →</span></a><a class="article" href="/intelligence-ai-search.html"><div class="homeHubMeta"><span class="tag">Digital Intelligence</span><span class="hubPulse"><i></i> Публикувано</span></div><h3>AI Search променя дигиталната видимост: от ranking към цитиране</h3><p>Google AI Overviews, click displacement и новата логика на Answer Intelligence.</p><span class="read">Прочети анализа →</span></a></div></div></section>`
	if strings.Contains(indexHTML, oldHub) {
		indexHTML = strings.Replace(indexHTML, oldHub, newHub, 1)
	}

	// Compact, contained public hero. The analytical artwork must never overflow
	// or create a large empty canvas at desktop or tablet widths.
	homeLayout := `<style id="blisHomeLayoutV4">
.hero{overflow:hidden!important}
.abstract{overflow:hidden!important;min-width:0!important}.abstract svg{display:block!important;max-width:100%!important;max-height:100%!important;object-fit:contain!important;transform:none!important}.floatCard{box-sizing:border-box!important}
@media(min-width:1101px){.hero,.heroInner{min-height:520px!important}.heroInner{gap:36px!important;grid-template-columns:1fr 1fr!important}.abstract{height:450px!important;width:100%!important;max-width:720px!important;justify-self:end!important}.abstract svg{width:94%!important;height:430px!important}.floatCard{right:12px!important;top:50%!important;bottom:auto!important;transform:translateY(-42%)!important;width:min(390px,calc(100% - 34px))!important;padding:18px!important}}
@media(min-width:721px) and (max-width:1100px){.hero,.heroInner{min-height:540px!important}.abstract{height:430px!important;top:46px!important;right:-5%!important;width:62%!important}.abstract svg{width:100%!important;height:410px!important}}
@media(max-width:720px){.hero,.heroInner{min-height:590px!important}.abstract{height:410px!important;top:70px!important;right:-18%!important;width:82%!important}.abstract svg{width:100%!important;height:390px!important}}
</style>`
	indexHTML = strings.Replace(indexHTML, `<style id="blisHomeLayoutV3">`, `<style id="blisHomeLayoutObsolete" media="not all">`, 1)
	if !strings.Contains(indexHTML, `id="blisHomeLayoutV4"`) {
		indexHTML = strings.Replace(indexHTML, `</head>`, homeLayout+`</head>`, 1)
	}

	indexHTML = strings.Replace(indexHTML, `<div><h4>Ресурси</h4><a href="#resources">Intelligence Hub</a><a href="/methodology.html">Методология</a><a href="#resources">Анализи</a><a href="#resources">Новини</a></div>`, `<div><h4>Intelligence Hub</h4><a href="/intelligence-hub.html">Всички материали</a><a href="/intelligence-retail-bulgaria-2026.html">Пазарни анализи</a><a href="/intelligence-reputation-trust.html">Репутация</a><a href="/intelligence-calendar.html">Редакционен календар</a></div>`, 1)
}
